name: Deploy to WordPress.org

on:
  pull_request:
  workflow_dispatch:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:
  deploy:
    name: Validate or deploy plugin
    runs-on: ubuntu-latest
    steps:
      - name: Check out plugin
        uses: actions/checkout@v4

      - name: Validate or deploy to WordPress.org
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          dry-run: ${{ github.event_name != 'push' }}
        env:
          VERSION: ${{ github.event_name == 'push' && github.ref_name || '3.0.9-test' }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
